name: CI
on:
  push:
    branches: ["master", "dev"]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Installing python linters and pytest
        run: pip install flake8 black isort pytest pytest_asyncio

      - name: Check prod with linters
        run: |
          isort --check .
          black --check .
          flake8 .

      - name: Check prod with pytest
        run: pytest

  deploy_job:
    needs: build_job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Stops all containers
        run: docker compose down

      - name: Build docker compose
        run: docker compose up --build -d

      - name: Wait for loading database
        run: sleep 10

      - name: Update alembic head
        run: docker compose exec web alembic upgrade head